export { GameMap } from './map/GameMap.ts';
export type { TileData } from './map/types.ts';
export { MapGenerator } from './map/MapGenerator.ts';
export { MapRenderer } from './map/MapRenderer.ts';
export { Noise, setNoiseSeed, getNoiseSeed, fbm } from './map/Noise.ts';
export { GameScene } from './scenes/GameScene.ts';
export { TimeSystem } from './systems/TimeSystem.ts';
export type { IClock } from './systems/TimeSystem.ts';
export { ErosionSystem } from './systems/ErosionSystem.ts';
export type { IErosionTarget, ErosionConfig } from './systems/ErosionSystem.ts';
export { CameraController } from './systems/CameraController.ts';
export { GameUI } from './ui/GameUI.ts';
export * from './constants.ts';
export * from './data/tiles.ts';
